server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  application:
    name: library-kata
  datasource:
    url: jdbc:h2:mem:librarykata
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
application:
  config:
    days-of-rental: 7